### ISSUE TITLE
Command Handlers

### ISSUE THREAD

**Issue by tcheeric** [avlo/nostr-relay#1]
Please note that the nostr-java's develop branch is now in version ```0.6-SNAPSHOT```. 

I have made some significant changes, for example, all ```nostr-java-ws-*``` artefacts were removed, and ```nostr-java-ws-handler-interface``` has been replaced with ```nostr-java-command-interface```. The provided default handler classes are in ```nostr-java-command-provider```. To build your own, you will need to add the ```CustomHandler``` annotation to your custom handler class.

**Comment by avlo** [comment]
thanks for the heads up, @tcheeric.  just FYI, nostr-relay's [server/session implementation](https://github.com/avlo/nostr-relay/blob/master/src/main/java/com/prosilion/nostrrelay/controller/NostrEventController.java) uses [Spring Session WebSocket architecture](https://docs.spring.io/spring-session/reference/guides/boot-websocket.html) and therefore did not require any former `nostr-java-ws-*` dependencies nor current `nostr-java-command-interface` dependency.

if i'm perhaps overlooking anything, please advise.

**Comment by avlo** [comment]
if useful/informative, here are `nostr-relay`'s `nostr-java` dependency classes:

```bash
$ grep -Hnri 'nostr\.' | sed 's/.*import//' | sort | uniq
 nostr.api.NIP01;
 nostr.api.Nostr;
 nostr.base.ElementAttribute;
 nostr.base.PublicKey;
 nostr.base.Signature;
 nostr.event.BaseEvent;
 nostr.event.BaseMessage;
 nostr.event.BaseTag;
 nostr.event.impl.ClassifiedListingEvent;
 nostr.event.impl.ClassifiedListingEvent.ClassifiedListing;
 nostr.event.impl.Filters;
 nostr.event.impl.GenericEvent;
 nostr.event.impl.GenericTag;
 nostr.event.impl.TextNoteEvent;
 nostr.event.json.codec.BaseMessageDecoder;
 nostr.event.json.codec.BaseMessageEncoder;
 nostr.event.Kind;
 nostr.event.list.EventList;
 nostr.event.list.FiltersList;
 nostr.event.list.KindList;
 nostr.event.list.PublicKeyList;
 nostr.event.Marker;
 nostr.event.message.CloseMessage;
 nostr.event.message.EventMessage;
 nostr.event.message.ReqMessage;
 nostr.event.NIP01Event;
 nostr.event.tag.EventTag;
 nostr.event.tag.PriceTag;
 nostr.event.tag.PubKeyTag;
 nostr.id.Identity;
 nostr.util.NostrUtil;
```
or in other words, limited to packages:

```bash
$ grep -Hnr 'nostr\.' | sed 's/.*import//' | sort | uniq | cut -d '.' -f 1,2 | uniq
 nostr.api
 nostr.base
 nostr.event
 nostr.id
 nostr.util
```

**Comment by avlo** [comment]
hi, @tcheeric, i'll close this issue (w/ resolution == "not planned") in ~24hours unless you've got issues/questions/advisement otherwise.

**Comment by tcheeric** [comment]
Go ahead and close. I updated my code, and I am now able to compile. Thanks. 
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


30 Apr 2024, 21:02 by ***@***.***:
