### ISSUE TITLE
[BUILD FAILURE] Could not resolve dependencies for project

### ISSUE THREAD

**Issue by delki8** [avlo/nostr-relay#4]
this is after cloning the repo and running `mvn clean install`

```
mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: ~/.sdkman/candidates/maven/current
Java version: 21.0.2, vendor: Oracle Corporation, runtime: ~/.sdkman/candidates/java/21.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-112-generic", arch: "amd64", family: "unix"
```

```
user@ubuntu:~/nostr/superconductor$ java --version
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-58)
OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
```

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.659 s
[INFO] Finished at: 2024-06-12T15:39:20-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project superconductor: Could not resolve dependencies for project com.prosilion:superconductor:jar:1.4.0: The following artifacts could not be resolved: nostr-java:nostr-java-api:jar:0.6, nostr-java:nostr-java-event:jar:0.6, nostr-java:nostr-java-id:jar:0.6: Could not find artifact nostr-java:nostr-java-api:jar:0.6 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by avlo** [comment]
Please refer to the project [README](https://github.com/avlo/superconductor/blob/master/README.md) for build instructions.

Contained within it are all the steps required to build the project, including the [Build and install nostr-java library](https://github.com/avlo/superconductor?tab=readme-ov-file#build-and-install-nostr-java-library) step you omitted.

**Comment by avlo** [comment]
btw, new upstream changes to [nostr-java/develop](https://github.com/tcheeric/nostr-java/tree/develop) are currently under [PR](https://github.com/tcheeric/nostr-java/pull/173) (to be merged within 48 hours)- which are used by superconductor, so if you'd like to build/use superconductor (either develop/master branch) before then, you can still do so by checking out [my fork of nostr-java/develop branch](https://github.com/avlo/nostr-java-avlo-fork/tree/develop) until then

**Comment by delki8** [comment]
Yes. I've been an idiot. Thanks for the patience, it works now.

**Comment by avlo** [comment]
superconductor is now available as a docker image and deployable via docker compose.  see the updated [README](https://github.com/avlo/superconductor?tab=readme-ov-file#normalproduction-mode-for-most-users-instructions) file for instructions.
