### ISSUE TITLE
Idea integration with superconductor

### ISSUE THREAD

**Issue by bolzobrazil** [avlo/nostr-relay#5]
Hi would these ideas be integrateable with superconductor?
https://github.com/nostr-protocol/nostr/issues/194
https://www.reddit.com/r/TOR/comments/1e4te8m/introducing_discussing_reflectors_as_concept/
https://lists.torproject.org/pipermail/tor-relays/2024-July/021744.htm**

**Comment by avlo** [comment]
the following NIPS functionally overlap your description/request:

https://nostr-nips.com/nip-04
https://nostr-nips.com/nip-28
https://nostr-nips.com/nip-53

however, they have not been integrated into superconductor (yet).

of the above listed, nip-04 will likely integrate first- however, there are several other nips currently prioritized before it.
